// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO4QPGaV8cQ02nLQNbtwhpJMP3p8CMWaI',
    appId: '1:676582625534:web:e6bef9bd5534db711d55af',
    messagingSenderId: '676582625534',
    projectId: 'refundweb-fc0ce',
    authDomain: 'refundweb-fc0ce.firebaseapp.com',
    storageBucket: 'refundweb-fc0ce.appspot.com',
    measurementId: 'G-RKTSD5458H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSzDSHb5Eiz9xUrH0jK7dLP3Sk9su5spg',
    appId: '1:676582625534:android:e9ab9ad333f9a94a1d55af',
    messagingSenderId: '676582625534',
    projectId: 'refundweb-fc0ce',
    storageBucket: 'refundweb-fc0ce.appspot.com',
  );
}
